### ISSUE TITLE
Wrong music tracks when using custom MSU soundtrack

### ISSUE THREAD

**Issue by ldperron** [Berserker66/MultiWorld-Utilities#115]
When using custom MSU soundtracks, the wrongs tracks are played at these two locations:
* Eastern palace: it plays the audio track that would normally be played with the video file, which is track 35 (0x23). Track 17 (0x11) should be played instead. 
* Outside skull woods: intro track (without triforce) is played. Which is track 15 (0x0F). Track 13 (0x0D) should be played instead.

**Comment by Berserker66** [comment]
This should be fixed with 2.3.3

**Comment by ldperron** [comment]
I tested with 2.3.3 today, still the same issue. Rom generated from alttpr.com has the exact same issue.
Weirdly, it was working properly in 2.2.1, with disablemusic=True and extendedmsu=0

**Comment by Berserker66** [comment]
That may be where the confusion is coming from. With 2.2.2 the extendedmsu option was dropped, as they're all extended msu. The same goes for alttpr.com now, they updated their extendedmsu to the same package.

**Comment by ldperron** [comment]
I was trying to find any source code or documentation reference for extended MSU v32, any clue where this project is?

**Comment by CaitSith2** [comment]
The base patch source code used by this repo is at https://github.com/CaitSith2/z3randomizer (forked from https://github.com/KatDevsGames/z3randomizer with multiworld changes cherry-picked from bonta's fork).  In any case, you are probably interested in msu.asm, music.asm and musicvolume.asm, within said source code.

**Comment by ldperron** [comment]
Thanks you very much! msu.asm gave me the right answer. I am indeed using an outdated pack.
By reading msu.asm, I noticed the fallback logic. So basically, removing files for track 15 and 35 fixes directly the problem without having to change anything else from the packs from Zeldix's site.
